version: '3.3'

services:
  picoweb:
    build:
      context: .
      dockerfile: Dockerfile-PicoWeb
    ports:
      - "7450:7450"
    restart: unless-stopped

  eagle-uml:
    build:
      context: ..
      dockerfile: docker/Dockerfile-EagleUml
    ports:
      - "95:5095"
    volumes:
      - E:/IdeaProjects/eagle-uml/htpasswd_dev:/project/htpasswd:ro
    environment:
      - SERVER_PORT=4100
      - PLANTUML_SERVER_URL=http://localhost:7450
    restart: unless-stopped
