version: '3.3'

services:
  picoweb:
    build:
      context: .
      dockerfile: Dockerfile-PicoWeb
    ports:
      - "7450:7450"
    restart: unless-stopped

  plant-uml-server:
    build:
      context: ../server
      dockerfile: Dockerfile-PlantUmlServer
    ports:
      - "7450:7450"
    restart: unless-stopped
