@startuml

autonumber

User -> Server :renderText
activate Server
Server -> RenderServer :sendText
activate RenderServer

Server <-- RenderServer
deactivate RenderServer
User <-- Server :image


@enduml
